# file: conda-macos-arm64.yaml
name: gpt4all
channels:
  - apple
  - conda-forge
  - huggingface
dependencies:
  - python>3.9,<3.11 # pin to 3.9 or 3.10 for now
  - tensorflow-deps
  - pip
  - onnxruntime
  - transformers
  - pip:
      # Apple Silicon
      # see: https://developer.apple.com/metal/tensorflow-plugin/
      - tensorflow-macos
      - tensorflow-metal # see TF issue https://stackoverflow.com/a/75973297/322358
      # Use nightly build for Tensorflow with --pre (preview)
      - --pre
      - --prefer-binary
      - --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      # - --extra-index-url https://download.pytorch.org/whl/torch_stable.html
      # - --extra-index-url https://download.pytorch.org/whl/cu116
      - --trusted-host https://download.pytorch.org
      - torch
      - torchvision
      - numpy
